apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: {{path.basename}}-
commonAnnotations:
  external-dns.alpha.kubernetes.io/hostname: {{path.basename}}.dev.zbsnu.click
resources:
- service.yaml
